#ifndef stmt_h
#define stmt_h

// WARNING: THIS FILE IS AUTOGENERATED
// Changes you make will not be kept.

/**
 * In loxc, a statment is just data and as such has no associated methods.
 * Instead, loxc makes use of the visitor pattern to visit statements. For
 * more information on each expression, and to add another one see
 * ../tools/loxc_statements.txt
 */

#include <memory> // std::shared_ptr
#include <variant>
#include <vector>
#include "expr.h"

using Stmt = std::variant<
	std::monostate,
	std::shared_ptr<struct PrintStmt>,
	std::shared_ptr<struct ExprStmt>,
	std::shared_ptr<struct VarStmt>,
	std::shared_ptr<struct BlockStmt> >;

struct PrintStmt
{
	Expr expression;

	PrintStmt (Expr expression_in)
		: expression(std::move(expression_in)) {}
};

struct ExprStmt
{
	Expr expression;

	ExprStmt (Expr expression_in)
		: expression(std::move(expression_in)) {}
};

struct VarStmt
{
	loxc::token name;
	Expr initializer;

	VarStmt (loxc::token name_in, Expr initializer_in)
		: name(std::move(name_in)), initializer(std::move(initializer_in)) {}
};

struct BlockStmt
{
	std::vector<Stmt> stmt_list;

	BlockStmt (std::vector<Stmt> stmt_list_in)
		: stmt_list(std::move(stmt_list_in)) {}
};

#endif